[tool.poetry]
name = "video-quality"
version = "0.1.0"
description = ""
authors = ["GStarP <1700066935@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scikit-image = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
